### ISSUE TITLE
Program to print all the odd numbers between 1 and 100.

### ISSUE THREAD

**Issue by samsiddiki** [hamzaumer2/Programming#1]

**Comment by hamza-umer** [comment]
#include<iostream>
using namespace std;
int main()
{
    int i=1;
        cout<<"All Odd number from 1 to 100 are: "<<endl;
  while(i<=100)
  {
    if(i%2==1)
    {
      cout<<i<<" ";
    }
  i++;
  }
  return 0;
}

**Comment by samsiddiki** [comment]
Ye toh very nice hai :p
